# .github/workflows/build-prefect-flow.yml
name: Build and Push Prefect Flow Image

on:
  push:
    branches: 
      - main
    paths:
      - 'pipeline-project/src/processing/**'
      - '.github/workflows/docker-build-push.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'pipeline-project/src/processing/**'
      - '.github/workflows/docker-build-push.yml'

env:
  PROJECT_ID: teak-gamma-442315-f8

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Docker auth'
      run: |
        gcloud auth configure-docker

    - name: Build and Push Docker image
      working-directory: pipeline-project/src/processing
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/taxi-flow:latest .
        docker push gcr.io/${{ env.PROJECT_ID }}/taxi-flow:latest