apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql-proxy
  namespace: data-pipeline
spec:
  selector:
    matchLabels:
      app: cloudsql-proxy
  template:
    metadata:
      labels:
        app: cloudsql-proxy
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command:
            - "/cloud_sql_proxy"
            - "-instances=teak-gamma-442315-f8:us-central1:data-pipeline-4039b51c=tcp:0.0.0.0:5432"
          volumeMounts:
            - name: gcp-key
              mountPath: /var/secrets/google
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: CLOUDSQL_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-credentials
                  key: connection_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-credentials
                  key: password
            - name: DB_NAME
              value: "pipeline_db"
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: "200m"
              memory: "200Mi" 
      volumes:
        - name: gcp-key
          secret:
            secretName: gcp-sa-key
---
apiVersion: v1
kind: Service
metadata:
  name: cloudsql-proxy
  namespace: data-pipeline
spec:
  selector:
    app: cloudsql-proxy
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
