apiVersion: v1
kind: Pod
metadata:
  name: gcp-test-pod
  namespace: data-pipeline
spec:
  containers:
  - name: gcp-test
    image: ero67/gcp-test:latest
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/secrets/google/key.json"
    volumeMounts:
    - name: gcp-key
      mountPath: "/var/secrets/google"
      readOnly: true
  volumes:
  - name: gcp-key
    secret:
      secretName: gcp-sa-key
  restartPolicy: Never