# k8s/base/prefect-agent.yaml (updated version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-agent
  namespace: data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
      - name: prefect-agent
        image: prefecthq/prefect:2-latest
        command: ["prefect", "worker", "start", "-p", "default-agent-pool", "-t", "process"]
        env:
        - name: PREFECT_API_URL
          value: "http://prefect-server:4200/api"
        - name: DB_HOST
          value: "cloudsql-proxy"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-credentials
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-credentials
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"