apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-server
  namespace: data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-server
  template:
    metadata:
      labels:
        app: prefect-server
    spec:
      containers:
      - name: prefect-server
        image: prefecthq/prefect:2-latest
        command: ["prefect", "server", "start"]
        args: ["--host", "0.0.0.0"]
        ports:
        - containerPort: 4200
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: prefect-server
  namespace: data-pipeline
spec:
  selector:
    app: prefect-server
  ports:
  - port: 4200
    targetPort: 4200
  type: ClusterIP