apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-agent
  namespace: data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
      - name: prefect-agent
        image: prefecthq/prefect:2-latest
        command: ["prefect", "worker", "start", "-p", "default-agent-pool", "-t", "process"]  # Updated to use worker instead of agent
        env:
        - name: PREFECT_API_URL
          value: "http://prefect-server:4200/api"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"