apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect-worker
  namespace: data-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefect-worker-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prefect-worker-role-binding
subjects:
- kind: ServiceAccount
  name: prefect-worker
  namespace: data-pipeline
roleRef:
  kind: ClusterRole
  name: prefect-worker-role
  apiGroup: rbac.authorization.k8s.io