# prefect-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-worker
  namespace: data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-worker
  template:
    metadata:
      labels:
        app: prefect-worker
    spec:
      containers:
      - name: prefect-worker
        image: gcr.io/teak-gamma-442315-f8/taxi-flow:latest
        command: ["prefect", "worker", "start"]
        args: ["-p", "k8s-pool"]
        env:
        - name: PREFECT_API_URL
          value: "http://prefect-server:4200/api"
        - name: PREFECT_LOGGING_LEVEL
          value: "DEBUG"
        - name: DB_HOST
          value: "cloudsql-proxy"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-credentials
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-credentials
              key: password
        - name: GCS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: pipeline-config
              key: GCS_BUCKET
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/var/secrets/google/key.json"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - name: gcp-key
          mountPath: "/var/secrets/google"
          readOnly: true
      volumes:
      - name: gcp-key
        secret:
          secretName: gcp-sa-key