apiVersion: v1
kind: Pod
metadata:
  name: storage-test-pod
  namespace: data-pipeline
spec:
  containers:
  - name: storage-test
    image: ero67/gcp-test:latest 
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/secrets/google/key.json"
    volumeMounts:
    - name: gcp-key
      mountPath: "/var/secrets/google"
      readOnly: true
  volumes:
  - name: gcp-key
    secret:
      secretName: gcp-sa-key
  restartPolicy: Never