apiVersion: batch/v1
kind: Job
metadata:
  name: taxi-data-flow-job
  namespace: data-pipeline
spec:
  template:
    spec:
      containers:
      - name: taxi-flow
        image: gcr.io/teak-gamma-442315-f8/taxi-flow:latest
        imagePullPolicy: Always
        command: ["python", "deploy.py"]
        env:
        - name: PREFECT_API_URL
          value: "http://prefect-server:4200/api"
        - name: PREFECT_LOGGING_LEVEL
          value: "DEBUG"
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: gcp-key
          mountPath: "/var/secrets/google"
          readOnly: true
        - name: temp-storage
          mountPath: "/Archive"
      volumes:
      - name: gcp-key
        secret:
          secretName: gcp-sa-key
      - name: temp-storage
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 2